schema {
    query: Query,
    mutation: Mutation,
}

type Query {
    getUser(): User
    hello(): String
}

type Mutation{
    createUser(name: String!): User
}

type User {
    id: Int
    name: String
}