schema {
    query: Query,
    # mutation: Mutation,
}

type Query {
    getUser(id: ID!): User
    hello(): String
}

type Mutation{
    createUser(name: String!): User
}

type User {
    id: ID
    name: String
}